### ISSUE TITLE
8 digit TFN validation

### ISSUE THREAD

**Issue by reecefenwick** [sidorares/tfn#1]
Hello,

Very cool module!

Has validation of 8 digit TFN's been intentionally left out?

**Comment by sidorares** [comment]
Hi, thanks!

can't remember. I see from the spec that 8 digit can form a valid TFN, I'm keen to add this ( or happy to merge PR if anyone can volunteer)

**Comment by sidorares** [comment]
Do you have an example 8 digit TFN? Would left padding with zero work?

**Comment by reecefenwick** [comment]
8 digit TFNs are really old and no longer issued. But still come up frequently enough to want to support them.

Attached a file which contains the algorithm for 8 digit TFNs, which is basically just different weightings.

[Tax_file_number_(TFN)_algorithm_8_digit.pdf](https://github.com/sidorares/tfn/files/290459/Tax_file_number_.TFN._algorithm_8_digit.pdf)

Raising a PR.
